---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/31 7:29 PM
---

require("eclass")

local Chello = class("hello")
local pystring = require("pystring")
local lmd = require("common.lmd")
local mdInst = lmd.new()

local function index(tReq)
    return {body = string.format("hello guys!")}
end

local function readme(tReq)
    local headers = {
        ["Content-Type"] = "text/html; charset=UTF-8",
    }
    local md = pystring.with("../README.md")
    return {headers = headers, body = mdInst:toHtml(md)}
end

function Chello:_init_(inst, conf)
    inst:get("/", index)
    inst:get("/readme", readme)
end

return Chello