---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2024/1/31 8:42 PM
---

require("eclass")
local ChttpReq = require("http.httpReq")

local Cproxy = class("proxy")

local function index(tReq)
    return {body = string.format("hello proxy!")}
end

local function proxy(tReq)
    local req = ChttpReq.new(tReq, "127.0.0.1", 2000)
    local tRes = req:get("/readme")
    return {headers = tRes.headers, body = tRes.body}
end

function Cproxy:_init_(inst, conf)
    inst:get("/", index)
    inst:get("/proxy", proxy)
end

return Cproxy